import { randomUUID } from 'node:crypto';
import type { Chunk, IndexState } from '../shared/types';
import { DocumentService } from './document-service';
import { PersistenceService } from './persistence-service';

export class IndexingService {
  private state: IndexState = { status: 'idle', documentCount: 0, chunkCount: 0, lastActivity: null };
  constructor(private readonly persistence: PersistenceService, private readonly documents: DocumentService) {}
  private chunk(documentId: string, text: string): Chunk[] { const paragraphs = text.split(/\n\s*\n/).map((part) => part.trim()).filter(Boolean); const groups: string[] = []; let current = ''; for (const paragraph of paragraphs) { if (current && current.length + paragraph.length + 2 > 500) { groups.push(current); current = ''; } if (paragraph.length > 500) { if (current) { groups.push(current); current = ''; } for (let offset = 0; offset < paragraph.length; offset += 500) groups.push(paragraph.slice(offset, offset + 500)); } else current = current ? `${current}\n\n${paragraph}` : paragraph; } if (current) groups.push(current); return groups.map((value, index) => ({ id: randomUUID(), documentId, index, text: value, characterCount: value.length, wordCount: value.split(/\s+/).filter(Boolean).length })); }
  async start(documentId?: string): Promise<IndexState> { this.state = { ...this.state, status: 'indexing', message: undefined }; try { const targets = documentId ? (await Promise.all([this.documents.get(documentId)])).filter((item): item is NonNullable<typeof item> => item !== null) : await Promise.all((await this.documents.list()).map((item) => this.documents.get(item.id))).then((items) => items.filter((item): item is NonNullable<typeof item> => item !== null)); let chunkCount = 0; for (const target of targets) { const chunks = this.chunk(target.document.id, target.content); chunkCount += chunks.length; await this.persistence.writeJson(`chunks/${target.document.id}.json`, chunks); await this.documents.updateStatus(target.document.id, 'indexed'); } const allDocuments = await this.documents.list(); const allChunks = await Promise.all(allDocuments.map((item) => this.chunks(item.id))); this.state = { status: allDocuments.length ? 'ready' : 'idle', documentCount: allDocuments.length, chunkCount: allChunks.reduce((sum, chunks) => sum + chunks.length, 0), lastActivity: new Date().toISOString(), message: `Indexed ${targets.length} document${targets.length === 1 ? '' : 's'} (${chunkCount} chunks).` }; return this.state; } catch (error) { this.state = { ...this.state, status: 'error', lastActivity: new Date().toISOString(), message: error instanceof Error ? error.message : 'Indexing failed.' }; return this.state; } }
  async status(): Promise<IndexState> { const documents = await this.documents.list(); const chunkSets = await Promise.all(documents.map((item) => this.chunks(item.id))); return { ...this.state, documentCount: documents.length, chunkCount: chunkSets.reduce((sum, chunks) => sum + chunks.length, 0) }; }
  async chunks(documentId: string): Promise<Chunk[]> { return this.persistence.readJson<Chunk[]>(`chunks/${documentId}.json`, []); }
}
