import { useCallback, useEffect, useState } from 'react';
import type { DocumentRecord, IndexState, QaResponse } from '../shared/types';
import { DocumentList } from './components/DocumentList';
import { QuestionPanel } from './components/QuestionPanel';
import { StatusBar } from './components/StatusBar';

const initialState: IndexState = { status: 'idle', documentCount: 0, chunkCount: 0, lastActivity: null };
export function App() { const [documents, setDocuments] = useState<DocumentRecord[]>([]); const [selectedId, setSelectedId] = useState<string | null>(null); const [detail, setDetail] = useState<{ document: DocumentRecord; content: string } | null>(null); const [history, setHistory] = useState<QaResponse[]>([]); const [state, setState] = useState(initialState); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { try { const [nextDocuments, nextState, nextHistory] = await Promise.all([window.knowledgeBase.documents.list(), window.knowledgeBase.indexing.status(), window.knowledgeBase.qa.history()]); setDocuments(nextDocuments); setState(nextState); setHistory(nextHistory); if (selectedId && !nextDocuments.some((item) => item.id === selectedId)) { setSelectedId(null); setDetail(null); } } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load the library.'); } }, [selectedId]);
  useEffect(() => { void refresh(); }, [refresh]); useEffect(() => { if (selectedId) void window.knowledgeBase.documents.get(selectedId).then(setDetail); }, [selectedId]);
  const importDocument = async () => { setError(null); try { const result = await window.knowledgeBase.documents.import(); if (result.document) setSelectedId(result.document.id); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Import failed.'); } };
  const deleteDocument = async () => { if (!selectedId) return; await window.knowledgeBase.documents.delete(selectedId); setSelectedId(null); setDetail(null); await refresh(); };
  const ask = async (question: string) => { setBusy(true); setError(null); try { const response = await window.knowledgeBase.qa.ask(question); setHistory((current) => [...current, response]); setState(await window.knowledgeBase.indexing.status()); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Question failed.'); } finally { setBusy(false); } };
  return <div className="app-shell"><header><div><span className="logo">K</span><div><h1>Knowledge Base</h1><p>Local answers, grounded in your documents</p></div></div><button className="secondary" onClick={() => void refresh()}>Refresh</button></header><aside><button className="import-button" onClick={() => void importDocument()}>＋ Import document</button><div className="section-heading"><span>Documents</span><b>{documents.length}</b></div><DocumentList documents={documents} selectedId={selectedId} onSelect={setSelectedId} /></aside><main><section className="content-panel">{error && <div className="error">{error}</div>}{detail ? <><div className="document-heading"><div><span className="eyebrow">{detail.document.filename}</span><h2>{detail.document.title}</h2><p>Imported {new Date(detail.document.importedAt).toLocaleString()}</p></div><div><button className="secondary" onClick={async () => { setState(await window.knowledgeBase.indexing.start(detail.document.id)); await refresh(); }}>Re-index</button><button className="danger" onClick={() => void deleteDocument()}>Delete</button></div></div><pre className="document-content">{detail.content}</pre></> : <div className="welcome"><span className="welcome-icon">⌁</span><h2>Your searchable knowledge, in one place</h2><p>Import .txt or .md documents, select one to read it, then ask questions below. Everything stays on this device.</p><button className="import-button" onClick={() => void importDocument()}>Import your first document</button></div>}</section><section className="answers"><div className="answers-heading"><h2>Answers</h2><span>{history.length} saved</span></div><div className="answer-list">{history.length === 0 ? <div className="answer-empty">Ask a question to search across indexed documents.</div> : [...history].reverse().map((item) => <article key={item.id}><h3>{item.question}</h3><p>{item.answer}</p><div className="confidence">Confidence {Math.round(item.confidence * 100)}%</div>{item.citations.map((citation) => <blockquote key={citation.chunkId}><strong>{citation.documentTitle}</strong>{citation.excerpt}</blockquote>)}</article>)}</div><QuestionPanel onAsk={ask} busy={busy} /></section></main><StatusBar state={state} /></div>; }
