const docs = [
  {title:'Remote Work Playbook',type:'PDF',pages:12,updated:'Opened today',eyebrow:'People & Culture · 2025',heading:'The Remote Work Playbook',dek:'A practical guide to building focused, connected, and high-performing distributed teams.',body:`<h2>Working with intention</h2><p>Remote work succeeds when teams replace proximity with clarity. That means documenting decisions, protecting focused time, and making communication norms explicit. The strongest distributed teams do not simply recreate the office online—they redesign how work moves.</p><div class="callout">“Default to transparency, but protect the time people need to do their best thinking.”</div><h2>Build an async-first rhythm</h2><p>Use written updates for status, decisions, and context. Reserve meetings for debate, creative collaboration, and sensitive conversations. Every meeting should have an owner, a clear outcome, and shared notes.</p><h2>Three operating principles</h2><p><strong>Clarity over immediacy.</strong> Define ownership and expected response times. <strong>Outcomes over activity.</strong> Measure what changes, not time online. <strong>Connection by design.</strong> Create deliberate moments for trust and belonging.</p>`},
  {title:'Q3 Product Strategy',type:'PDF',pages:18,updated:'Yesterday',eyebrow:'Product · Q3 Planning',heading:'Q3 Product Strategy',dek:'Turning customer insight into a focused roadmap for sustainable growth.',body:`<h2>Strategic direction</h2><p>This quarter focuses on activation, team collaboration, and enterprise readiness. Customer interviews consistently show that teams understand the product value but need a faster path to their first successful workflow.</p><div class="callout">Our primary goal is to reduce time-to-value from seven days to under one day.</div><h2>Key bets</h2><p>We will simplify onboarding, introduce reusable workspace templates, and improve administrative controls. Success will be measured through activation rate, weekly engaged teams, and expansion revenue.</p>`},
  {title:'Research Synthesis',type:'DOC',pages:8,updated:'Aug 8',eyebrow:'Research · Customer insights',heading:'Research Synthesis',dek:'What we learned from 24 interviews with growing knowledge-work teams.',body:`<h2>Executive summary</h2><p>Users value speed and simplicity, but confidence is the strongest predictor of long-term adoption. People need to understand where information came from and what action to take next.</p><h2>Recurring themes</h2><p>Participants described fragmented context, repetitive searching, and uncertainty around the latest version of a document. Teams asked for concise answers with visible citations and easy access to the original source.</p>`},
  {title:'Brand Guidelines',type:'PDF',pages:24,updated:'Aug 2',eyebrow:'Brand · Edition 2.1',heading:'Brand Guidelines',dek:'A shared system for expressing our identity with warmth, precision, and purpose.',body:`<h2>Our design philosophy</h2><p>Clarity should feel calm, capable, and human. We use generous space, purposeful typography, and an earthy palette to help people focus on what matters.</p><div class="callout">Every detail should reduce effort or add meaning.</div><h2>Voice principles</h2><p>Be direct without being cold. Prefer familiar words, active sentences, and specific guidance. Respect the reader's time and intelligence.</p>`}
];
let active=0, zoom=100, page=1;
const list=document.getElementById('documentList'),paper=document.getElementById('paper'),question=document.getElementById('question'),sendBtn=document.getElementById('sendBtn'),chat=document.getElementById('chat');
function renderList(){list.innerHTML=docs.map((d,i)=>`<button class="doc-item ${i===active?'active':''}" data-i="${i}"><span class="doc-icon">${d.type}</span><strong>${d.title}</strong><small>${d.updated}</small></button>`).join('');document.getElementById('docCount').textContent=docs.length;list.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=+b.dataset.i;page=1;renderList();renderDoc();resetChat()})}
function renderDoc(){const d=docs[active];document.getElementById('crumbTitle').textContent=d.title;document.getElementById('pageInfo').textContent=`${d.pages} pages`;document.getElementById('pageNumber').textContent=`${page} / ${d.pages}`;paper.innerHTML=`<div class="eyebrow">${d.eyebrow}</div><h1>${d.heading}</h1><div class="dek">${d.dek}</div>${d.body}<div class="meta"><span>Clarity workspace</span><span>Page ${page}</span><span>Updated August 2026</span></div>`;paper.style.transform=`scale(${zoom/100})`}
function resetChat(){chat.innerHTML=`<div class="welcome"><div class="orb">✦</div><h2>What would you like to know?</h2><p>Ask anything about this document. I’ll find the answer and point you to the source.</p></div><div class="suggestions" id="suggestions"><button>Summarize this document</button><button>What are the key recommendations?</button><button>List the main action items</button></div>`;wireSuggestions()}
function wireSuggestions(){document.querySelectorAll('#suggestions button').forEach(b=>b.onclick=()=>ask(b.textContent))}
function answerFor(q){const d=docs[active],lower=q.toLowerCase();if(lower.includes('summar'))return `${d.dek} The document emphasizes ${d.title==='Remote Work Playbook'?'clear communication, intentional asynchronous work, outcome-based measurement, and deliberately designed team connection.':'a focused set of principles and practical actions that teams can apply immediately.'}`;if(lower.includes('action')||lower.includes('recommend'))return d.title==='Remote Work Playbook'?'The main recommendations are to document decisions, set explicit response-time norms, protect focus time, reserve meetings for high-value collaboration, assign every meeting an owner, and measure outcomes rather than online activity.':'Prioritize the main themes described in the document, assign a clear owner to each initiative, define a measurable outcome, and review progress on a regular cadence.';return `Based on “${d.title},” the central idea is that ${d.dek.toLowerCase()} The document supports this through practical principles and examples designed to turn the strategy into consistent action.`}
function ask(text){if(!text.trim())return;document.querySelector('.welcome')?.remove();document.getElementById('suggestions')?.remove();chat.insertAdjacentHTML('beforeend',`<div class="message user">${escapeHtml(text)}</div><div class="message answer typing">•••</div>`);chat.scrollTop=chat.scrollHeight;setTimeout(()=>{document.querySelector('.typing').outerHTML=`<div class="message answer"><div class="answer-head">✦ Answer</div>${answerFor(text)}<div class="source"><strong>Source</strong> · ${docs[active].title}, page ${page}</div></div>`;chat.scrollTop=chat.scrollHeight},450);question.value='';sendBtn.disabled=true}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.getElementById('askForm').onsubmit=e=>{e.preventDefault();ask(question.value)};question.oninput=()=>sendBtn.disabled=!question.value.trim();question.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();ask(question.value)}};document.getElementById('clearChat').onclick=resetChat;
document.getElementById('plus').onclick=()=>{zoom=Math.min(130,zoom+10);document.getElementById('zoom').textContent=zoom+'%';renderDoc()};document.getElementById('minus').onclick=()=>{zoom=Math.max(70,zoom-10);document.getElementById('zoom').textContent=zoom+'%';renderDoc()};document.getElementById('prev').onclick=()=>{page=Math.max(1,page-1);renderDoc()};document.getElementById('next').onclick=()=>{page=Math.min(docs[active].pages,page+1);renderDoc()};
document.getElementById('searchInput').oninput=e=>{const term=e.target.value.trim();renderDoc();if(term){const re=new RegExp(`(${term.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')})`,'gi');paper.innerHTML=paper.innerHTML.replace(/>([^<]+)</g,(m,t)=>`>${t.replace(re,'<mark>$1</mark>')}<`)}};
document.getElementById('addBtn').onclick=async()=>{const file=await window.docu.pickDocument();if(!file)return;docs.push({title:file.name.replace(/\.[^.]+$/,''),type:file.type,pages:1,updated:'Just now',eyebrow:`Imported · ${file.type}`,heading:file.name.replace(/\.[^.]+$/,''),dek:'An imported document in your Clarity workspace.',body:`<h2>Document content</h2><p>${escapeHtml(file.content).replace(/\n+/g,'</p><p>')}</p>`});active=docs.length-1;renderList();renderDoc();resetChat();const toast=document.getElementById('toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)};
renderList();renderDoc();wireSuggestions();
